### ISSUE TITLE
As an evaluator I want to easily view public good projects and make evaluations.

### ISSUE THREAD

**Issue by Oba-One** [greenpill-dev-guild/impact-reef#25]
# Done State

-  I want to be able to easily view public goods projects
-  I want to be able to make evaluations
-  I want to be able to identify relevant evaluation schemas according to the project I'm viewing - 
-  I want the be able to identify relevant projects according to the type of information I want to evaluate
-  I want to be able to view evaluations that I've made
-  I want to be able to view evaluations I've made for a project
-  I want to be able to view evaluations made for a project

# Tasks

- [ ] greenpill-dev-guild/impact-framework-backend#26
- [ ] greenpill-dev-guild/impact-framework-backend#28
- [ ] greenpill-dev-guild/impact-framework-backend#30
- [ ] greenpill-dev-guild/impact-framework-backend#32
- [ ] greenpill-dev-guild/impact-framework-backend#33

# Technical Requirements

- Design follow guideline outlined in [PRD](https://app.charmverse.io/impact-visualization/impact-evaluation-prd-9030869483317048)
- Typescript used for React components
- Storybook used for creating components

# Resources

- [Figma Designs](https://www.figma.com/file/T9gqqMmCGQFZHppwvAJW8G/Designs?type=design&node-id=4149-12292&mode=design)
- [EAS](https://attest.org/)
- [Gitcoin Explorer](https://explorer.gitcoin.co/)
