### ISSUE TITLE
As a user I want to easily login with my social accounts or wallet.

### ISSUE THREAD

**Issue by Oba-One** [greenpill-dev-guild/impact-reef#39]
# Done State

- [ ] greenpill-dev-guild/impact-framework-backend#40
- [ ] greenpill-dev-guild/impact-framework-backend#41
- [ ] greenpill-dev-guild/impact-framework-backend#42
- [x] greenpill-dev-guild/impact-framework-backend#43

# Technical Requirements

- Design follow guideline outlined in [PRD](https://app.charmverse.io/impact-visualization/impact-evaluation-prd-9030869483317048)
- Typescript used for React components
- Storybook used for creating components

# Resources

- [Figma Designs](https://www.figma.com/file/T9gqqMmCGQFZHppwvAJW8G/Designs?type=design&node-id=4149-12292&mode=design)
